version: '2'
services:    
    www:
      build: ./docker/www
      ports :
       - "9080:80"
      links:
       - db
      volumes:
        - ./public_html:/home/inforex/public_html
        - ./local:/home/inforex/local
        - ./engine:/home/inforex/engine
        - ./docker/www/config:/home/inforex/config
        - ./secured_data:/home/inforex/secured_data
      depends_on:
      - db
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
       - "7080:80"
      depends_on:
       - db
    liuqibase:
      build: ./docker/liquibase
      links:
      - db
      depends_on:
      - db
      volumes:
      - ./database:/workdir/database
      working_dir: /workdir
      command: /bin/bash run.sh
    db:
      image: mysql:5.7
      ports:
       - "3333:3306"
      environment:
         TZ: "Europe/Rome"
         MYSQL_ALLOW_EMPTY_PASSWORD: "no"
         MYSQL_ROOT_PASSWORD: "password"
         MYSQL_USER: 'inforex'
         MYSQL_PASSWORD: 'password'
         MYSQL_DATABASE: 'inforex'
      command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      volumes:
       - ./database/init:/docker-entrypoint-initdb.d

