-- add stage field to tokens_tags_optimized

ALTER TABLE  `tokens_tags_optimized`
ADD  `stage` ENUM(  'tagger',  'agreement',  'final' )
CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  'tagger'
COMMENT  'Describes stage of chosen tag, tagger- generated by tagger, agreement- set by user, final- set by final user with agreement check';