#! /bin/sh
# $1 nazwa pliku do testu

time java -cp /home/czuk/nlp/workspace/lingpipe/lingpipe-3.8.2.jar:/home/czuk/nlp/workspace/lingpipe/demos/tutorial/ne/neDemo.jar TrainConll2002 gpw.model $1.train $1.train
time java -cp /home/czuk/nlp/workspace/lingpipe/lingpipe-3.8.2.jar:/home/czuk/nlp/workspace/lingpipe/demos/tutorial/ne/neDemo.jar TestConll2002Chunker  gpw.model $1.test | tee $1.log
rm gpw.model
